
language: dart
dart:
  - stable
jdk:
  - openjdk8
  
install:
  -sudo install curl
  
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  
  
