
language: dart
dart:
  - stable
jdk:
  - openjdk8
  
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

  
before_script:
#   - git clone https://github.com/Motaung08/Innovative-Skyline -b beta
  - ./flutter/bin/flutter doctor
  
  
