# codecov:
#   require_ci_to_pass: yes


# coverage:
#   precision: 2
#   round: down
#   range: "70...100"

# parsers:
#   gcov:
#     branch_detection:
#       conditional: yes
#       loop: yes
#       method: no
#       macro: no

# comment:
#   layout: "reach,diff,flags,tree"
#   behavior: default
#   require_changes: no

coverage:
  status:
    project:
      default:
        # basic
        target: 0%
        threshold: 0%
        base: 0%
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
