ignore:
  - "lib/View/Board.dart"
  - "lib/View/register/StudentRegister.dart"
  - "lib/View/Home"
  - "lib/test/ControllerTests/DegreeController_test.dart"
  - "lib/test/ControllerTests/ListController_test.dart"
  - "lib/test/ControllerTests/StudentController_test.dart"
  - "lib/test/ControllerTests/SupervisorController_test.dart"
  - "lib/test/ControllerTests/TaskStatusControll_test.dart"
  - "lib/test/ControllerTests/UserController_test.dart"
  - "lib/test/ControllerTests/StudentTypeController_test.dart"
